[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "model"
version = "1.0.1"
description = ""
dependencies = [
    "joblib==1.4.2",
    "matplotlib==3.10.0",
    "pandas==2.2.3",
    "scikit-learn==1.6.1",
    "mlflow===2.20.2"
]
